name: Build and Push Docker Image

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.MY_DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_PASSWORD}}

      - name: Build Docker image
        run: docker build -t rizulgupta636/java-demo:latest .

      - name: Push Docker image
        run: docker push rizulgupta636/java-demo:latest
